# Generated by Django 4.2.7 on 2026-02-15 06:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Investor first name', max_length=100)),
                ('last_name', models.CharField(help_text='Investor last name', max_length=100)),
                ('email', models.EmailField(help_text='Unique email address', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', help_text='Contact phone number', max_length=20)),
                ('investor_type', models.CharField(choices=[('LP', 'Limited Partner'), ('GP', 'General Partner')], help_text='Limited Partner or General Partner', max_length=2)),
                ('share_amount', models.DecimalField(decimal_places=2, help_text='Total committed investment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('shares_owned', models.IntegerField(default=0, help_text='Number of shares/units owned', validators=[django.core.validators.MinValueValidator(0)])),
                ('entry_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='One-time entry fee amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quarterly_payment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Recurring quarterly payment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', help_text='KYC verification status', max_length=10)),
                ('kyc_verified_date', models.DateField(blank=True, help_text='Date when KYC was verified', null=True)),
                ('investor_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', help_text='Current investor status', max_length=10)),
                ('joined_date', models.DateField(help_text='Date when investor joined the project')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal admin notes about the investor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this investor record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_investors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['investor_type'], name='investors_i_investo_4d4bbd_idx'), models.Index(fields=['kyc_status'], name='investors_i_kyc_sta_0d8f47_idx'), models.Index(fields=['investor_status'], name='investors_i_investo_409552_idx'), models.Index(fields=['email'], name='investors_i_email_154f7d_idx')],
            },
        ),
    ]
