# Generated by Django 4.2.7 on 2026-02-15 06:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('ENTRY_FEE', 'Entry Fee'), ('QUARTERLY', 'Quarterly Payment'), ('SHARE_PURCHASE', 'Share Purchase'), ('OTHER', 'Other')], help_text='Type of payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Current status of the payment', max_length=10)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('WIRE', 'Wire Transfer'), ('CHECK', 'Check'), ('CASH', 'Cash'), ('OTHER', 'Other')], help_text='Payment method used', max_length=20)),
                ('payment_date', models.DateField(help_text='Date when payment was made')),
                ('due_date', models.DateField(blank=True, help_text='Expected payment due date', null=True)),
                ('verification_date', models.DateTimeField(blank=True, help_text='Date and time when payment was verified', null=True)),
                ('reference_number', models.CharField(blank=True, default='', help_text='Bank reference or transaction number', max_length=100)),
                ('quarter', models.CharField(blank=True, default='', help_text='Quarter identifier (e.g., Q1 2024)', max_length=10)),
                ('receipt_document', models.FileField(blank=True, help_text='Uploaded payment receipt or proof', null=True, upload_to='payment_receipts/%Y/%m/')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about the payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(help_text='Investor making this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='investors.investor')),
                ('verified_by', models.ForeignKey(blank=True, help_text='User who verified this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['payment_status'], name='payments_pa_payment_8ac9aa_idx'), models.Index(fields=['payment_type'], name='payments_pa_payment_09c1c1_idx'), models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'), models.Index(fields=['investor', 'payment_status'], name='payments_pa_investo_df37ff_idx'), models.Index(fields=['due_date'], name='payments_pa_due_dat_752274_idx')],
            },
        ),
    ]
